### PR TITLE
Fix/511 guides singular for one result

### LINKED ISSUE #511: [Bug]: When one guide is found it says '1 guides found'
## Description

Screenshot 2023-06-21 at 12 09 21

### PR DESCRIPTION
**Pull request by r-ferrier**
Fixes #511

## Description

- Introduces new keys for singular search results in english and welsh
- Refactors slightly how these are generated in view (sorry @katjam for any merge headaches - just wanted to split this string creation logic out from the rest of the view to keep it easier to follow)

@geeksforsocialchange/developers

### CODE REVIEW

**Comment by r-ferrier** [comment]
Actually i've just refactored my refactoring to make it more alike the existing setup while still moving the string generation logic out of the view. Shouldn't cause too many issues now!

File: src/I18n/En.elm [hunk 1]
```diff
@@ -185,6 +185,9 @@ enStrings key =
         SearchTitleFiltered num query ->
             num ++ " guides on " ++ query
 
+        SearchTitleFilteredSingleResult query ->
```
Comment (katjam) [inline src/I18n/En.elm:188]: It's better to handle the logic here so people using it don't have to remember to add logic in the view & because languages have different methods for pluralisation. https://www.gnu.org/software/gettext/manual/gettext.html#Plural-forms

Comment (katjam) [reply src/I18n/En.elm:188]: This may well be what you did in the first iteration! Sorry. Anyway, it's standard practice to pass a number and a pluralisable translation and expect the translation to handle it.

**Review by katjam — CHANGES_REQUESTED** [review]
You may have done it this way on first pass, but we should move the logic into the translation function.

File: src/I18n/En.elm (hunk 1 above)
Comment (r-ferrier) [reply src/I18n/En.elm:188]: ah! Of course, that makes more sense. Am changing.

Comment (r-ferrier) [reply src/I18n/En.elm]: have also nicked the concatenation method you switched to in your PR

**Review by katjam — APPROVED** [review]
Great
