### PR TITLE
Fix story layout snafu

### LINKED ISSUE #260: [Bug]: fix layout issue on story page
## Description

When clearing #113 I found the following layout glitch on the "show story" page

https://team-wilder-proto.pages.dev/stories/test-story-with-minimal-fields

Screenshot_2023-05-29_16-24-27

### PR DESCRIPTION
**Pull request by ivan-kocienski-gfsc**
Fixes #260

Screenshot_2023-06-01_15-16-09

Turns out our two column layout doesn't behave well with content of a fixed width.

@geeksforsocialchange/developers

### CODE REVIEW

File: src/Page/Story/View.elm [hunk 1]
```diff
@@ -116,3 +116,10 @@ imageCaptionStyle : Style
 imageCaptionStyle =
     batch
         [ margin3 (rem 0) (rem 0) (rem 1) ]
+
+
+imageSizeFixStyle : Style
+imageSizeFixStyle =
```
Comment (r-ferrier) [inline src/Page/Story/View.elm:122]: Is there are reason why this width couldn't be added in to the existing featureImageStyle? I think the feature image is only used in one other place, and is it possible that the same thing could be happening there that is happening here? 

I ask because having separate styles that you add one at a time like this can get really confusing unless they're absolutely necessary to change the behaviour of the original css. Also the name of this is more like a PR comment than a reference to what the styles are actually doing - shouldn't it be called something like image100PctWidth if this needs to be kept as a separate style?

Comment (ivan-kocienski-gfsc) [reply src/Page/Story/View.elm]: You make a good point.

I have moved the rule into the `featureImageStyle` which is used in show Guide and show Story views.

My first solution was trying to be conservative and only fixing the one problem in isolation but i suppose such an approach could easily make spaghetti css.

File: src/Theme/Global.elm [hunk 2]
```diff
@@ -245,7 +245,7 @@ featureImageStyle =
     batch
         [ width (pct 100)
         , height auto
-        , maxWidth (px (maxSmallDesktop / 3))
+        , maxWidth (pct 100)
         , teaserRowStyle
         ]
```
[the remark this answers is not in the document]
Comment (ivan-kocienski-gfsc) [reply src/Theme/Global.elm:249]: I took it out. seems to work fine without it.

**Review by r-ferrier — APPROVED** [review]
