### PR TITLE
Fix/223 tests and lint

### LINKED ISSUE #223: [Bug]: Tests failing & not running during deploy pipeline
## Description

Tests should be running automatically some point in our pipeline. Probably on Pull Request creation as suggested in #3 

As part of this - run `elm-review` to tidy up the code.

### PR DESCRIPTION
**Pull request by katjam**
Fixes #223

## Description

- Fix tests
- Lint code with `elm-review`
- Run tests on pre-push
- Remove unused relationship between stories and guides (NOTE: we might want this back)

@geeksforsocialchange/developers

### CODE REVIEW

File: tests/Story.elm [hunk 1]
```diff
@@ -104,7 +85,7 @@ suite =
                         queryFromStyledHtml (view storyFull)
                             |> Query.contains
                                 (List.map
-                                    (\image -> Html.img [ Html.Attributes.alt image.alt, Html.Attributes.src image.src ] [])
+                                    (\image -> Html.img [ Html.Attributes.alt image.alt, Html.Attributes.src image.src, Html.Attributes.class "_570ce029" ] [])
```
Comment (katjam) [inline tests/Story.elm:88]: Not ideal with the class hash but was after a quick fix. It may not change unless styles change - so probably ok.

File: src/Page/Guide/View.elm [hunk 2]
```diff
@@ -149,7 +148,7 @@ viewRelatedGuideTeasers language guideTitleList allGuidesSlugTitleList =
             , ul [ css [ listStyleNone ] ]
                 (List.map
                     (\item ->
-                        li [] [ a [ href item.slug ] [ text (titleFromLanguage language item) ] ]
+                        li [] [ a [ href (Route.toString (Guide item.slug)) ] [ text (titleFromLanguage language item) ] ]
```
Comment (aaaaargZombies) [inline src/Page/Guide/View.elm:151]: now I'm looking at this I'm surprised it was working in the first place

File: src/Page/Guide/View.elm [hunk 3]
```diff
@@ -140,7 +139,7 @@ viewRelatedGuideTeasers language guideTitleList allGuidesSlugTitleList =
     in
     if List.length relatedGuideItems > 0 then
         let
-            t : I18n.Keys.Key -> String
+            t : Key -> String
```
Comment (aaaaargZombies) [inline src/Page/Guide/View.elm:142]: elm-review doesn't like the import path style that we use elsewhere?

**Review by aaaaargZombies — APPROVED** [review]
looks good, test on push will make a big difference to keeping the tests up to date

File: src/Page/Guide/View.elm (hunk 3 above)
Comment (katjam) [reply src/Page/Guide/View.elm:142]: No I was bringing this into line with our style for Key elsewhere. We aren't totally consistent on it - but this is the only place it was qualified with `I18n` because there was an accidental import of the `Browser.Navigation.Key` in this file which forced it to be qualified.

File: src/Page/Guide/View.elm (hunk 2 above)
Comment (katjam) [reply src/Page/Guide/View.elm:151]: Yes - this also confused me. There is another pattern used with the teasers that include images - so we do need to check that's all resolving correctly.
