### PR TITLE
Video styling

### LINKED ISSUE #182: [Bug]: Video styles broken
## What happened?

View a guide with a video - the video overlapped other content and was small.

## What were you expecting to happen?

See a video not overlapping other content & full width

## Steps to reproduce
image

## Platform (if relevant)

What device and browser were you using?

### PR DESCRIPTION
**Pull request by ivan-kocienski-gfsc**
Fixes #182

## Description

- fixes how images are embedded in markdown

@geeksforsocialchange/developers

### CODE REVIEW

**Review by r-ferrier — CHANGES_REQUESTED** [review]
It's not collapsing any more which is brill but it still looks really small! Are you able to dig into it a little bit more and see if you can get it to fill the column?

**Comment by ivan-kocienski-gfsc** [comment]
Not sure if that is possible as the size of the video is entirely down to youtube as it's in an `iframe`. The iframe is filling the width of the column but the video is just hanging out on the left on its own

**Comment by r-ferrier** [comment]
Maybe try this?

On the iframe:

```
height: 100%;
left: 0;
position: absolute;
top : 0;
width: 100%;
```
& on the iframe's parent container:

```
paddingBottom: 56.25%;
position: relative;
width: 100%;
```
This forces it to display without black borders, at full size and height, assuming videos all come in at this ratio - for now I think as they're likely to all be youtube links it's a fairly safe assumption to make? 

If it turns out they're not we can try something else in future!

**Comment by ivan-kocienski-gfsc** [comment]
Have done the additions

**Review by r-ferrier — CHANGES_REQUESTED** [review]
Works a treat! Just one last change request

**Comment by katjam** [comment]
@ivan-kocienski-gfsc I've promised to have the site ready for them to add content by Tuesday morning. No need to do anything here until you are next in, but wanted let you know that I might go ahead and do this last change myself on Monday. If @r-ferrier is also in, she can check this and my other PRs.

**Comment by katjam** [comment]
@ivan-kocienski-gfsc Just checking one more time if it's OK for me to fix this up on your behalf since your on another project at the moment.

File: src/Page/Shared/View.elm [hunk 1]
```diff
@@ -180,3 +181,24 @@ viewGuideTeaserList includeSummary teasers =
...
+
+embeddedVideoStyle : Style
+embeddedVideoStyle =
+    batch
+        [ height (pct 100)
+        , left zero
+        , position absolute
+        , top zero
+        , width (pct 100)
+        , maxWidth (px (Theme.Global.maxTabletLandscape / 3))
```
Comment (katjam) [inline src/Page/Shared/View.elm:194]: This makes the video not full width on a bigger screen. So I thought, maybe do we want to center it? But leaving left until another decision is made.

Comment (r-ferrier) [reply src/Page/Shared/View.elm:194]: Sorry, I don't think I made that very clear - the styles I suggested were meant to entirely replace those inside embeddedVideoStyle, so that it would not have a maxWidth any more, it's no longer necessary with the new layout
